### ISSUE TITLE
Sort consumers per current consumption

### ISSUE THREAD

**Issue by Sixdsn** [davet2001/energy-sankey#87]
Hello,

First of all, just installed the live card and love it!
I dont know how easy it might be to do but having the option to view the consumers by highest current power would be great.

Thanks,

**Comment by davet2001** [comment]
Looking at it a bit more, I agree. Sorting by default is probably ok. But I think the sort should always be followed with 'other' and 'untracked' at the bottom.

**Comment by davet2001** [comment]
This is implemented in 0.0.21 (currently in pre-release). 
At the moment I'm finding it's working on energy but not power cards - I'm not sure why yet.

Any other feedback would be helpful if others can try the pre-release. Thanks!

**Comment by convicte** [comment]
It does seem to sort things quite OK, but may have negative effects in form of a nonexistent solar variable I do not have in my config.

![Screenshot_20250517_122232_Home Assistant.jpg](https://github.com/user-attachments/assets/c84c5dbc-ba1a-4dfb-a074-6cc6fd7a26de)

```yaml
type: custom:hui-power-flow-card
title: Live power flow
consumer_entities:
  - entity: sensor.nilan_switch_power
  - entity: sensor.livingroom_sockets_power
  - entity: sensor.lights_power
  - entity: sensor.seaside_curtain_power
  - entity: sensor.roadside_curtain_power
  - entity: sensor.kitchen_led_power
  - entity: sensor.toaster_power
  - entity: sensor.coffee_maker_power
  - entity: sensor.dishwasher_power
  - entity: sensor.washing_machine_power
  - entity: sensor.kids_floor_heating_power
  - entity: sensor.bedroom_floor_heating_power
  - entity: sensor.livingroom_floor_heating_power
battery_entities: []
config_version: 2
invert_battery_flows: false
power_from_grid_entity: sensor.total_power_draw
hide_small_consumers: false
max_consumer_branches: 0
```

Hope this helps!
