### ISSUE TITLE
Not Displaying Data

### ISSUE THREAD

**Issue by DeFlanko** [davet2001/energy-sankey#88]
Got an odd one for you. Just trying to add these to a dashboard and no data shows on them, one of them just spins forever and cant select it. 

![Image](https://github.com/user-attachments/assets/08250232-ca0c-47c8-9fbf-1bb2da092724)

![Image](https://github.com/user-attachments/assets/076b3ca2-c91e-4eec-9ecd-e1b5f8793b4d)

![Image](https://github.com/user-attachments/assets/f82e54c2-7e41-46a1-8922-1b8a13e76670)

```yaml
auto_update: false
display_precision: 0
installed_version: v0.0.18
in_progress: false
latest_version: v0.0.18
release_summary: null
release_url: https://github.com/davet2001/energy-sankey/releases/v0.0.18
skipped_version: null
title: null
update_percentage: null
friendly_name: Energy Sankey Card update
supported_features: 23
```

![Image](https://github.com/user-attachments/assets/563339f4-dd8e-4f59-8421-9a04d5366ad1)
